### ISSUE TITLE
Flatpak/Snap support

### ISSUE THREAD

**Issue by ghost** [BOINC/boinc#2485]
Dear developers,

could you provide Flatpak and/or Snap support for Linux distributions? Both are new packaging formats that work distribution independently and offer sandbox isolation and other other neat features.

Regards

Jakob

**Comment by TheAspens** [comment]
In the duplicate issue #2715 - @davidpanderson noted:

> email on boinc_alpha:
> 
> I am not succeeding in running BOINC with openSUSE. The program opens but does not communicate with the server. It's running on Slackware but it was not something simple. I had to follow specific instructions. Is not it possible to package BOINC using flatpak?

**Comment by jakobjakobson18** [comment]
An initial flatpak manifest could look similar to the following one:
```
app-id: org.boinc.boinc
runtime: org.freedesktop.Platform
runtime-version: "18.08"
sdk: org.freedesktop.Sdk
command: ???
modules:
  - name: wxWidgets
    buildsystem: autotools
    config-opts:
      - --with-gtk
      - --disable-shared
    sources:
      - type: archive
        url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.4/wxWidgets-3.0.4.tar.bz2
        sha256: 96157f988d261b7368e5340afa1a0cad943768f35929c22841f62c25b17bf7f0

#  - name: libnotify
#    buildsystem: autotools
#    sources:
#      - type: git
#        url: git://salsa.debian.org/gnome-team/libnotify

  - name: boinc
    buildsystem: simple
    build-commands:
      - ./_autosetup
      - ./configure --disable-server --enable-client CXXFLAGS="-O3 "
      - make
      - cd packages/generic/sea/
      - make
    sources:
      - type: git
        url: git://github.com/BOINC/boinc

```

Without the `libnotify` section the manifest succeeds in building the `wxWidgets` and going into the `boinc` build process. However in that case the libnotify library is missing.

With the `libnotify` section the manifest can't pull the libnotify git repository (even though I don't understand why).

**Comment by jakobjakobson18** [comment]
As boinc provides a script that extracts the needed files, the following manifest could also be a starting point:

```
app-id: org.boinc.boinc
runtime: org.gnome.Platform
runtime-version: '3.28'
sdk: org.gnome.Sdk
command: boinc
modules:
- name: boinc
  buildsystem: simple
  build-commands:
  - ???
  - ???
  sources:
  - type: file
    url: https://boinc.berkeley.edu/dl/boinc_7.2.42_x86_64-pc-linux-gnu.sh
    sha256: 7fa10f06047c0a7fa3c2554f75b3aff503ec2bdfe7c95e9040981b1d29a536df

````

With this approach boinc has not be compiled for each installation of the users as the precompiled files are used.


Regards

**Comment by AenBleidd** [comment]
The only issue here is with this script: it is too old and probably need to be updated if it is still supportable way to distribute BOINC for linux

**Comment by truboxl** [comment]
I would vouch my support for AppImage packaging for the next BOINC Linux release. It's more akin to macOS dmg and provides other benefits that other packaging do include and don't.

Flatpak, as of right now, still doesn't work with OpenCL / CUDA out of the box...

**Comment by rugk** [comment]
BTW I personally would prefer flatpak. In contrast to snap, you can also self-host it, so you stay in control, and it is widely supported. (snap is not so nice to setup in many distros and snap's security depends on AppArmor, which is not always available in many distros)
Also – in contrast to snaps – flatpaks do not only claim to be distro-independent, but [actually are](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/).

**Comment by jakobjakobson13** [comment]
Hi guys,

with the following file you can compile the boinc binaries if that helps in any way.

```
app-id: org.boinc.boinc  # can be altered
runtime: org.gnome.Platform
runtime-version: '3.26'
sdk: org.gnome.Sdk
command: boinc
finish-args:
  - --share=network
  - --socket=x11
  - --socket=fallback-x11
  - --share=ipc
  - --socket=wayland
  - --device=dri
modules:
- name: wxWidgets
  config-opts:
  - --with-gtk
  - --disable-shared
  sources:
  - type: archive
    url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
    sha256: fffc1d34dac54ff7008df327907984b156c50cff5a2f36ee3da6052744ab554a
- name: boinc
  buildsystem: simple
  build-commands:
  - ./_autosetup
  - ./configure --disable-server --enable-client --prefix=${FLATPAK_DEST}
  - make install
  sources:
    - type: archive
      url: https://github.com/BOINC/boinc/archive/client_release/7.16/7.16.6.tar.gz
      sha256: caa567da8d3eb50859efe2eeba1c23c7b27d3b0f15b548136e75302713b25303
```
